[browser]
gatherUsageStats = false

[server]
# The address where the server will listen for client and browser connections. Use this if you want to bind the server to a specific address. If set, the server will only be accessible from this address, and not from any aliases (like localhost).
# Default: (unset)
# address =

[theme]
base="light"
primaryColor="#b439df"